version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
region = "eu-central-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ptc9lcm3pezt"
s3_prefix = "spotify-f2p"
stack_name = "spotify-f2p"
