app: spotify-f2p
org: luismeyer
service: spotify-f2p

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "secretsmanager:DescribeSecret"
        - "secretsmanager:GetSecretValue"
        - "secretsmanager:CreateSecret"
        - "secretsmanager:PutSecretValue"
      Resource: "*"

functions:
  sync:
    handler: ./src/app.handler
    events:
      - schedule: cron(0 */1 * * ? *)
