service: spotify-f2p-app
frameworkVersion: "3"
variablesResolutionMode: 20210326

useDotenv: true

provider:
  name: aws
  region: eu-central-1
  stage: dev
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    BITLY_SECRET: ${env:BITLY_SECRET}
    FRONTEND_URL: ${env:FRONTEND_URL}
    BACKEND_URL: ${env:BACKEND_URL}
    SPOTIFY_CLIENT_SECRET: ${env:SPOTIFY_CLIENT_SECRET}
    SPOTIFY_CLIENT_ID: ${env:SPOTIFY_CLIENT_ID}

plugins:
  - serverless-jetpack
  - serverless-iam-roles-per-function
  - serverless-s3-sync
  - serverless-dynamodb-local
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}

  config:
    table: ${self:custom.stage}-f2p-table
    bucket: ${self:custom.stage}-f2p-frontend

  s3Sync:
    buckets:
      - bucketName: ${self:custom.config.bucket}
        localDir: packages/frontend/dist

  dynamodb:
    stages:
      - dev
    inMemory: false
    start:
      port: 8000
      seed: true
      migrate: true

  jetpack:
    preInclude:
      - "!**"
    trace:
      ignores:
        - "aws-sdk"

package:
  individually: true
  excludeDevDependencies: true

functions:
  auth:
    handler: packages/auth/build/handler.handle
    events:
      - http:
          path: /auth
          method: get
          cors: true
    package:
      include:
        - packages/auth/**
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
        Resource:
          - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.config.table}"
          - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.config.table}/index/*"
    environment:
      TABLE_NAME: ${self:custom.config.table}

  sync:
    handler: packages/sync/build/handler.handle
    events:
      - http:
          path: /sync
          method: get
          cors: true
    timeout: 900
    package:
      include:
        - packages/sync/**
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource:
          - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.config.table}"
          - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.config.table}/index/*"
    environment:
      TABLE_NAME: ${self:custom.config.table}

resources:
  Resources:
    Table:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.config.table}

    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.config.bucket}
        WebsiteConfiguration:
          ErrorDocument: "index.html"
          IndexDocument: "index.html"

    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref WebsiteBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action: "s3:GetObject"
              Principal: "*"
              Resource: !Sub "${WebsiteBucket.Arn}/*"
