AWSTemplateFormatVersion: 2010-09-09

Description: >-
  spotify-f2p

Transform: AWS::Serverless-2016-10-31

Resources:
  Auth:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda that authorizes Users for the spotify sync
      Runtime: nodejs12.x
      Handler: build/handlers/auth.authHandler
      Timeout: 900
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: "/auth/"
            Method: get
      Policies:
        - Statement:
            - Sid: F2PAuthRole
              Effect: Allow
              Action:
                - "dynamodb:GetItem"
                - "dynamodb:PutItem"
                - "dynamodb:CreateTable"
              Resource: "*"
  Api:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that syncs spotify songs
      Runtime: nodejs12.x
      Handler: build/handlers/api.apiHandler
      Timeout: 900
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: "/api/"
            Method: get
      Policies:
        - Statement:
            - Sid: F2PSyncRole
              Effect: Allow
              Action:
                - "dynamodb:GetItem"
                - "dynamodb:PutItem"
              Resource: "*"
  Sync:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that syncs spotify songs
      Runtime: nodejs12.x
      Handler: build/handlers/sync.syncHandler
      Timeout: 900
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: "/sync/"
            Method: get

  Error:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that syncs spotify songs
      Runtime: nodejs12.x
      Handler: build/handlers/gateway.timeoutHandler
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: "/error/"
            Method: get
