name: Deploy master branch

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  BITLY_SECRET: ${{ secrets.BITLY_SECRET }}
  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
  BACKEND_URL: ${{ secrets.BACKEND_URL }}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install
        id: install
        run: npm ci

      - name: Compile
        id: compile
        run: npm run compile

      - name: Build
        id: build
        run: npm run build

      - name: Deploy Frontend
        run: npm run deploy:s3 -- --stage prod

      - name: Deploy Backend
        run: npm run deploy:sls -- --stage prod
